### PR TITLE
Initial documentation for new Content Philosophies

### PR DESCRIPTION
**Pull request by RayBenefield**
We are redefining our process thanks to almost a year of seeing how things are working now. These are the proposed changes which push for more clarity in stage definition. In particular, it focuses on more Team Projects and reducing the overload on the Beta stage.

### CODE REVIEW

**Review by Darkprince909 — COMMENTED** [review]
Doesn't seem to let me comment on a particular line, so... Generally I agree with most of the new changes, though I feel like going from Alpha to Beta, especially when you consider what most people in the forge community consider to be a 'beta', just texturing a blockout that's reached Alpha stage will seem a little underwhelming, even for this stage in development. I know you want that 'WOW' factor on release, but I don't think anyone's going to get excited about a blockout with textures. If, in addition to the texturing, we did sort of 'broad strokes' aesthetics (ex. the final map needs an ornate fireplace. Beta should have a fireplace, but in its simplest form. Couple blocks, and a fire effect.) This would help sell the eventual theme that the map would have, but still leave lots of room for visual improvements.

Also, keeping the lightmap under 100% shouldn't always be a hard and fast rule. Maps have made it into MM with lightmaps far over 100%, and I've seen lots of maps that look just fine at 300% with no hits to performance. It's all situational.

**Comment by Malevolution** [comment]
Though there are a couple of things that I have concerns with, like naming and the lack of developing design for Beta, I say we should at least give this a run-through for a few sprints to just see if this works for the better or worse.

**Comment by RayBenefield** [comment]
What exactly are your concerns @Malevolution?

**Comment by matthew-willis** [comment]
I really enjoy the thought of these changes. I believe that most of usual concerns will be handled with the changes in our philosophy and how we approach the projects. There are few things that I want to cover, that I either misread or didn't see. 

1, We need to make sure that we remember that we are going in this as team. We aren't going to lean on one person to develop the level or design the map to a theme. This is a collaborative effort. We have share the same stake at this. 
2. We also need to be mindful of how we treat our fellow members and community members. It's okay to share your personal thoughts and disgruntles, but be mindful, people are looking at us. To include 343 and the rest of the community. If they see any of us bashing on something in a destructive manner, not only will it reflect on you badly, it will look bad for the entire team.
3. One of my favorite leadership philosophies that I try to follow is this "If you ever want to become a great leader, you must learn how to be a great follower first". So take this for instance, if Cliff is in charge of said art on a certain project, learn to follow his direction and guidance regardless of how much you hate the approach. If it turns out that the art is complete crud, this is the time for feedback. Then the leader should take that feedback and use that to his advantage and reattack the project. Don't attack the project leads, learn from it. Work together in the most efficient way as possible.
4. I still feel like we need some way cycle through to cycle through projects. There are several people on the team that have ideas, level designs, art themes, etc. We need to make sure that everyone has the ability to provide something unique for the team.
5. We need to remember that everyone can't join everyday, at the same time. But what we can do is focus on whether there is a lobby or not, working on the current project. With that we need to make sure that we do our due diligence and update the card and who owns the most recent copies.
6. I think all projects, up until Release (or beta) need to be set to private. We need to share things and yes, get into the community. But, what I don't want to happen is for a someone to take a non-playable version and have false impressions on map that wasn't intended to played upon. This may take some work to do, but I think it's something to think about.

I believe that's all that I have to say, for now at least.

**Comment by C-Kennelly** [comment]
Overall, I like it, and I'm definitely down to try it.  I especially like the focus on content delivery, and rotating project leads means that the "overhead" of directing the team's efforts will be spread around more - really good for burnout, imo.  I would suggest that the Design and Aesthetic Leads are the ones with final calls on design and art choices for that map, as they will be responsible for pushing the vision in each of their respective areas.

After we try it for a while, I'd also like to experiment with two teams - essentially a Red and a Blue team that could work on two pieces of content (a Release and a Beta) much like we did with Breakout and Fury this last month.  I do not think we should start this way, as getting everyone on the same page will be enough of a challenge for the start.

Also, after the automation component of our sprint is evolved enough, I'd like to check the automation code into this repo along with the philosophy.  It would facilitate trying out new ways of doing things, and then our processes will be truly version controlled.

**Comment by CausticKirby** [comment]
I am definitely going to be more part of bringing the people in initially with aesthetics don't quite understand peoples ideal gameplay mechanics yet, part of that probably has to do with the fact that I don't quite understand people on any other basis either...

**Review by Randy-355 — COMMENTED** [review]
- Original Philosophy
  I agree with everything here. The Beta stage really did feel like a Full release, and lots did bottleneck here.
- Goals of the New Philosophy
  I especially like the idea of having a single release style sprint. Get people excited to move something out quick.
- The New philosophy
  I like the way Content Stages are labeled here. Simple. This list here should be everywhere as a reminder.

I like the idea of a WIP thread. Overtime, this thread showing from Beta to Release, the writeup will basically write itself.

Amen to credit towards Creative Force only on release. This allows the team to focus on the project itself, and less on ownership. We're a team, dammit!
- Future Philosophy
  I like the idea of creating a design document as the first thing done for a project. My 'Halo CE Library Infection' will get this treatment as a test run for myself.

**Review by Randy-355 — COMMENTED** [review]
- Idea - Existence
  I also like what I'm reading here. We should make it a point to post in as many Sandbox and Mindbox cards as we can to ensure collaboration and that no opportunities are missed.
- Prototype Acknowledgement
  All this makes sense. (No art Randy, NO ART.)
- Alpha - Soul
  Noted. Quick stage, change almost only gameplay, and set up as much gametype required items as possible. Test this shit! Have an art direction planned. (Don't actually DO the art Randy. Just have it in mind.)
- Beta - Identity
  Here we go, just make a foundation for the art. Halo CE. Halo CE. Halo CE. Make a WIP thread!
- Release - Style
  Do the art! Get fancy! Make this shit look good! Will be and should be the most exciting phase. I'd love to see the whole team collab on just one thing for releases.

So, as far as the WIP threads go, who should be in charge of this? I feel like it should be made clear. One of the Leads I assume?

**Comment by C-Kennelly** [comment]
I'd imagine the two Leads can split it. The ideal WIP thread in my mind is created by the Design Lead, and has a section on Design and Aesthetics.

The design doc that the Designer is making can be the content for the initial post, and the Aesthetic lead can add reference images (and later, screenshots) in another post, as well as describe the planned direction. 

Knell's WIP thread uses this organization, if anyone would like a picture of what I have in mind.

**Review by AlexVan123 — COMMENTED** [review]
More dev notes and things helps my job A LOT. I think a lot of this will work out well.

**Review by CryptokidFH — COMMENTED** [review]
This seems like a step in the right direction for our productivity as well as our overall appearance to the community. My only concern with the addition of a GitHub is that it is one more thing for new members to keep track of. Personally, and it might be just me, but I sometimes have trouble staying caught up / keeping track of everything between the two Trellos, the Slack, the occasional stuff on FH and now this as well. I'm sure if I had more free time it wouldn't be as much of a problem, but sometimes I feel a bit overwhelmed by how many different sources we've got.

I'd really like to get started on running map tests, but I'm so out of touch with how things run now that I don't know where to begin to get a reliable player-base for internal / external. I think this system will help with the other problem I was worried about, which was knowing what I was supposed to be testing and what was ready for what kind of test, so hopefully this will help smooth things out for me.

**Comment by PixelatedGuy** [comment]
All of this sounds really good to me. I haven't had much chance to contribute to the actual creation of maps yet. Jumping into a party with several of us working together would give me an opportunity to be more hands-on. I can add to the project in my own simple babyforger way while learning from you more experienced blokes at the same time.

**Comment by GenoGiovanini** [comment]
This all sounds good to me. It will be something I will need to get use too. Do we have a standard map we should use for most of our forge maps? Or is this up to the designer to decide on? 

I'm excited for this I have always enjoy our team efforts on a project. We will definitely get a lot of content accomplish by this method.

**Review by black-picture — COMMENTED** [review]
i am reviewing -picture that is black

**Comment by matthew-willis** [comment]
[GitHub Test Repo](https://trello.com/c/r8RLV3OG/6-github-test-repo)

**Pull request merged**
